AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false


Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
