AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - Gemfile
    - Rakefile

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Exclude:
    - test/**/*
