Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
